name: SkillRunes
version: 2.0
main:  me.kav.mythicalrunes.Main
softdepend: [EffectLib, WorldGuard, WorldEdit]
commands:
   runes:
      description: Runes root command
      usage: /<command>
   hellohello:
      description: testing utils
      usage: /<command>